"""Message de la migration, comme 'Ajout de champ last_game_attempt'

Revision ID: 6b3d7961c66b
Revises: ecc98e69ff79
Create Date: 2024-11-07 02:19:03.590836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b3d7961c66b'
down_revision = 'ecc98e69ff79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_game_attempt', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_game_attempt')

    # ### end Alembic commands ###
